version: '3.1'
services:

  rabbitmq:
    build: .
    environment: 
      RABBITMQ_DEFAULT_USER: my_user
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - 8080:15672
      - 5672:5672
      - 25676:25676
